### PR TITLE
HOT FIX: Access series and movies from TV Show and Movie categories

### LINKED ISSUE #196: Trying to play any video shows a popup telling user to update the extension.
While already being on the latest version (2.7.1)

### PR DESCRIPTION
**Pull request by arvvoid**
## Please check that your pull request pass this checks:

-  [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [x] My code is both Python 2 and 3 compatible
-  [x] My code follows the code style of this project (PEP8, long lines allowed if make sense)
-  [x] I made sure there wasn't another Pull Request opened for the same update/change
-  [x] I have successfully tested my changes locally

## Types of changes

-  [x] Bug fix (non-breaking change which fixes an issue)
-  [ ] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

After some api change trying to playback a show or movie from TV Shows or Movies category result in error. Trying playback from other locations like search, my list, home lists was not affected by the problem.

### CODE REVIEW

**Comment by arvvoid** [comment]
TESTERS NEEDED:

This needs some in-depth user testing before release.
Please test playback of both movies and tv shows from all categories (My list, continue watching, search, tv shows, movies, various home lists).
Please report here the results both positive and negative with full debug logs of all performed actions.

Please write in short the tests performed and the outcome and in addition attach a full debug log tnx

Before running the tests clear the request cache of your add-on:

120322748-0ad59180-c2e5-11eb-9f65-22d2376de30f


TEST ZIP FOR Kodi 18 Leia:

REMOVED

TEST ZIP FOR Kodi 19 Matrix:

REMOVED

**Comment by razorxster** [comment]
Hi,

i tested the new stuff, but nothong started :(

I tried movies, tv shows. From different categories, from search and continue watching also.

Full kodi log attached.
[kodi3.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/6640294/kodi3.log)

**Comment by razorxster** [comment]
Hi,

i restarted the PI, now stream have been started again.

Movies from:
search: OK
watch continue: OK
several categories: OK

TV shows:
search: OK
news: OK
watch continue: OK
several categories: Not OK the same message af 2.7.1

Kodi Log attached.
[kodi4.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/6640371/kodi4.log)

**Comment by arvvoid** [comment]
Hello @razorxster partial log, not usefully.

Anyway looks like playback start normally for you now every time, it fails then in inputstream.adaptive witch means you have a different problem now completely unrelated to this.
So the problem is not in the add-on for you now.

`2021-06-11 20:08:17.208 T:1335877856   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation`

Since your log is not complete i have not enough info to advise you further.
If you are on rpi you problem might be this: https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

**Comment by razorxster** [comment]
Please check my last comment.

**Comment by arvvoid** [comment]
@razorxster ok, glad it worked, the log is still partial and not complete. Just to make sure have you cleared the request cache as advised before testing? Some of the urls look strange and should not be there unless they remained in cache from before (they will expire in 24h)

**Comment by razorxster** [comment]
Hi,

i cleared the cache of course. That was my first step.

**Comment by arvvoid** [comment]
Ok can you tell me please exactly what menu->series caused the error so I can try to recreate my side.

EDIT: In all my tests i just performed all is fine. In the first log you posted kodi3.log the urls are fine and consistent with the test version. The second log posted the urls make no sense and look exactly like should look like in 2.7.1 so something is not right.

Waiting for more testers and more logs from different users.

**Comment by ArturSierzant** [comment]
In my case everything works fine. Thanks for your effort.

Regards
Artur

**Comment by arvvoid** [comment]
Tnx for testing. This should be stable for merging and release now. I would like a test and debug logs as test result for this release candidate version:

In this version debug mode is turned off in the add-on by default so before running tests in addition to enabling debug logging in Kodi, debug mode has to be enabled in the add-on. After the log is done and there is no more need for debug remember to turn it off in the add-on settings as well to improve add-on performance.

Image 12-06-2021 at 17 51


Kodi 18 Leia:

REMOVED

Kodi 19 Matrix:

REMOVED

**Comment by arvvoid** [comment]
This is ready for merging. With my testing and other reports here end elsewhere it seems good to go, since it fix something currently doesn't work anyway no point in holding this further.
Will get wider testing once released.

**Pull request merged**
