### PR TITLE
Fix encoding problem if profile paths with unicode characters

### PR DESCRIPTION
**Pull request by arvvoid**
## Please check that your pull request pass this checks:

-  [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [x] My code is both Python 2 and 3 compatible
-  [x] My code follows the code style of this project (PEP8, long lines allowed if make sense)
-  [x] I made sure there wasn't another Pull Request opened for the same update/change
-  [x] I have successfully tested my changes locally

## Types of changes

-  [x] Bug fix (non-breaking change which fixes an issue)
-  [ ] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

Related to ISSUE #146

### CODE REVIEW

**Comment by arvvoid** [comment]
Hello @petakpa1 this is the pull request containing the fix for the problem you reported in issue #146 

Please test and even if all seams ok take debug logs and post them here so I can confirm the issue is solved include stuff not directly visible on the interface:

[REMOVED]

Edit please test this fixed test version:

18.x Leia:
[plugin.video.hbogoeu-2.5.6-leia-beta2.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4474884/plugin.video.hbogoeu-2.5.6-leia-beta2.zip)

(OPTIONAL)
19.x Matrix: 
[plugin.video.hbogoeu-2.5.6-matrix-beta2.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4474885/plugin.video.hbogoeu-2.5.6-matrix-beta2.zip)

**Comment by gbelovai** [comment]
Thanks @arvvoid! It seems the 2.5.6 beta solved the failed playback issue.
debug log: https://paste.kodi.tv/galonoyoge.kodi

**Comment by arvvoid** [comment]
@gbelovai Yes, looking at the log all is fine now. I need just confirmation from @petakpa1 as well. 
And someone to test and confirm that the fix is good for the Nordic/Spain region as well and can merge this and will be included in next release.

**Comment by petakpa1** [comment]
Dear All,

Thank you for your fast job. I confirm that above linked 2.5.6. beta version is working at me on W10 + Kodi 18.4 Leia system.  Unfortunately I cannot test it on Kodi 19 Matrix version.

Kind regards,
Peter

**Comment by arvvoid** [comment]
Tested Kodi 19 (Python 3) as expected is fine with or without these changes

**Comment by arvvoid** [comment]
Hello, @Sakerdot @sanangel @PolliSoft @macardi @jhdgghost @jumakki @Evili84 @haakobja can someone please test this branch and report back. I just need to make sure this doesn't break anything for Nordic/Spain region before merging :)

**Comment by PolliSoft** [comment]
> 
> 
> Hello, @Sakerdot @sanangel @PolliSoft @macardi @jhdgghost @jumakki @Evili84 @haakobja can someone please test this branch and report back. I just need to make sure this doesn't break anything for Nordic/Spain region before merging :)

I installed it, and logged in without a problem. However, in this version I lost all subtitles on all videos. I reinstalled the Master branch version, and I got all subtitles back.

**Comment by arvvoid** [comment]
@PolliSoft tnx, can you please take a full debug log (perform playback) with this version and post it so I can fix the problem.

**Comment by PolliSoft** [comment]
@arvvoid here it is: https://pastebin.com/1KBw2hxc
Let me know if I can do anything else.

**Comment by arvvoid** [comment]
@PolliSoft Please test this and report back with a log:

Leia Kodi 18.x: 
[plugin.video.hbogoeu-2.5.6-leia-beta3.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4485796/plugin.video.hbogoeu-2.5.6-leia-beta3.zip)

Matrix Kodi 19.x (OPTIONAL IF YOU CAN, not test on primary device Kodi 19 is in alpha):
[plugin.video.hbogoeu-2.5.6-matrix-beta3.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4485803/plugin.video.hbogoeu-2.5.6-matrix-beta3.zip)

**Comment by PolliSoft** [comment]
@arvvoid 
Kodi 18.6 Test Ok, log here: https://pastebin.com/QtYPSxV0 

Kodi 19 (20200415-75732613) Test Not Ok, steps below:
1. Clean install of Kodi 19 OK
2. Install HBO GO and all dependencies, via zip file provided. OK
3. Start HBO GO and login (I did not try to start any video). OK
4. Exit HBO GO, enable debug logging in Kodi, enable debug logging in HBO GO. OK
5. Restart Kodi, start HBO GO. NOK, see log https://pastebin.com/4sZ8mtFV

Kodi 19 (20200415-75732613) Test Ok, steps below:
1. As above, but debug logging turned off in HBO GO. OK
Log here: https://pastebin.com/krL8cweu

**Comment by arvvoid** [comment]
Thank you @PolliSoft that is useful information this should fix the issue with debug log in Matrix, please try playback and subtitles as well on 19 if you can:

Leia: 
[plugin.video.hbogoeu-2.5.6-leia-beta4.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4486352/plugin.video.hbogoeu-2.5.6-leia-beta4.zip)

Matrix:
[plugin.video.hbogoeu-2.5.6-matrix-beta4.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4486354/plugin.video.hbogoeu-2.5.6-matrix-beta4.zip)

**Comment by PolliSoft** [comment]
No worries @arvvoid , happy to help!
Matrix Test ok, log: https://pastebin.com/NETR5X1n 
Leia Test ok, log: https://pastebin.com/fLETj2XT

**Comment by arvvoid** [comment]
@PolliSoft Ok perfect thank you.

**Pull request merged**
