### PR TITLE
Fix some of the pylint warnings

### PR DESCRIPTION
**Pull request by Ajnasz**
## Please check that your pull request pass this checks:

-  [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [x] My code is both Python 2 and 3 compatible
-  [x] My code follows the code style of this project
-  [x] I made sure there wasn't another Pull Request opened for the same update/change
-  [x] I have successfully tested my changes locally

## Types of changes

-  [x] Bug fix (non-breaking change which fixes an issue)
-  [ ] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

Hey!

My vim setup automatically check the python code with https://www.pylint.org/ and it shows a bunch of warnings to me. I started to fix at least a few of them. Let me know if you agree with these changes. :)
It shows a lot of warnings about long lines, I ignored them for now, that could be a separate pr I think.
And many warnings shown about the instance variables like `COUNTRY_CODE_SHORT`. I would change all of them to `snake_case` (`country_code_short` here), if you don't mind.

### CODE REVIEW

**Comment by arvvoid** [comment]
Hello, the repository and pull requests are also checked by codacy automatically on every push using bandit (for code security) and pylint for both py2 and 3 and some other tools as well. By default pylint make lot of noise and warnings that are just subjective matter sometimes, on codacy is already fine-tuned/configured to warn or throw errors only about important stuff.

For instance variables like COUNTRY_CODE_SHORT i made them capital letters on purpose, all variables related to the hbo go API that are used to build API URLs or payloads are in capital letters. 

Thanks you for your work on this and your contributions, the changes you made look fine, and make some of the variable names more intuitive and clear.
Will look in detail tomorrow and run a quick test on py2 an 3 and merge if you think is ready for merging.

**Comment by arvvoid** [comment]
Tested both handler py2 and 3 all good.
This is ready for merging if you give the ok.

**Review by arvvoid — APPROVED** [review]

**Comment by arvvoid** [comment]
I also enabled these checks in codacy to keep it consistent in the future

**Comment by Ajnasz** [comment]
Thanks, yes, you can merge it.

Can I see the codacy config somehow?

**Comment by arvvoid** [comment]
I will see if there is a way to share the codacy config

**Comment by arvvoid** [comment]
Go to https://app.codacy.com/manual/arvvoid/plugin.video.hbogoeu/dashboard?bid=14568459 to see the codacy report or click on the code quality badge in the readme.md

EDIT: fixed the rest of style issues in other files reported by codacy

**Comment by Ajnasz** [comment]
> Go to https://app.codacy.com/manual/arvvoid/plugin.video.hbogoeu/dashboard?bid=14568459 to see the codacy report or click on the code quality badge in the readme.md, some more issue apered now but nothing to worry about just import orders and else used with return after fixing those few lest all will match the same style

Yes, I've seen that, but I can't see the settings for the project, so I
can't configure it locally. :)

And also, there is no way to export the configuration from codacy:
https://support.codacy.com/hc/en-us/articles/115002130625/comments/115000082993
And that is sad! :(

Thanks anyway!

**Comment by arvvoid** [comment]
I think i will add to the TODO list to migrate all the codacy configs for bandit, pylint ecc to config files in the repo and configure codacy to use the config files in the repo instead of internal config, the option exists.

That way the config will be clear and sharable.

**Pull request merged**
