### PR TITLE
Python 2/3 compatibility fixes

### PR DESCRIPTION
**Pull request by arvvoid**
## Please check that your pull request pass this checks:

-  [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [X] My code is both Python 2 and 3 compatible
-  [X] My code follows the code style of this project
-  [X] I made sure there wasn't another Pull Request opened for the same update/change
-  [X] I have successfully tested my changes locally

## Types of changes

-  [X] Bug fix (non-breaking change which fixes an issue)
-  [X] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

Python 3 compatibility will require some more work, all work will be done on this branch witch will be merged after its well tested and stable on both Kodi 18 with Python2 and Kodi 19 test build with Python3

Kodi 19 Python3 TestBuild Win64: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190907-e0bfcd95-PR16116-merge-x64.exe

Kodi 19 Python3 TestBuild MacOS: http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20190907-e0bfcd95-PR16116-merge-x86_64.dmg

THIS NEED TESTING especially for Spain/Nordic region that I can't fully test myself.

### CODE REVIEW

**Comment by Ajnasz** [comment]
I needed to add these changes to list "new" items and the ones that available for the last time, for Hungarian locale:

https://github.com/arvvoid/plugin.video.hbogoeu/compare/python3-compatibility-fixes...Ajnasz:python3-compatibility-fixes

**Comment by Ajnasz** [comment]
And this one too
https://github.com/Ajnasz/plugin.video.hbogoeu/commit/c7936243cadc0ef1501f6010f64e1a7159d92d90

**Comment by arvvoid** [comment]
@Ajnasz thank you, I merged your changes into the branch. 
I will start detailed testing after I finish with some changes, to make the credential system both Python2 and 3 compatible.

**Comment by arvvoid** [comment]
@Ajnasz I reverted your the changes back for the moment. But the current master of this branch should work with no issues on Kodi 18 Python2. If you can pls test.

Python3 will not work atm, no need to test that, but getting there.

**Comment by arvvoid** [comment]
Both Python2 Kodi 18, Python3 Kodi19 work now.

This now needs more testing especially Spain/Nordic version.
Need login test from someone on Cyfrowy Polsat on Python3 Kodi19 and Python2 Kodi18

Playback isn't fully tested on Python 3 Kodi 19 because I can't find a working inputstream.adaptive for Kodi PR16116 TestBuild with Python3 support for now.

**Comment by arvvoid** [comment]
This now is stable enough for a release and general testing. Going to merge the changes an make a release soon for wider testing.

**Pull request merged**
