### PR TITLE
Update ttml2str

### PR DESCRIPTION
**Pull request by arvvoid**
## Please check that your pull request pass this checks:

-  [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [x] My code is both Python 2 and 3 compatible
-  [x] My code follows the code style of this project (PEP8, long lines allowed if make sense)
-  [x] I made sure there wasn't another Pull Request opened for the same update/change
-  [x] I have successfully tested my changes locally

## Types of changes

-  [x] Bug fix (non-breaking change which fixes an issue)
-  [ ] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

Fix issue #157

### CODE REVIEW

**Comment by arvvoid** [comment]
Leia test version:
[plugin.video.hbogoeu-2.5.11-leia-beta1.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4538981/plugin.video.hbogoeu-2.5.11-leia-beta1.zip)

Matrix test version:
[plugin.video.hbogoeu-2.5.11-matrix-beta2.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4538985/plugin.video.hbogoeu-2.5.11-matrix-beta2.zip)

**Comment by arvvoid** [comment]
Leia:
[plugin.video.hbogoeu-2.5.11-leia-beta3.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4539305/plugin.video.hbogoeu-2.5.11-leia-beta3.zip)

Matrix:
[plugin.video.hbogoeu-2.5.11-matrix-beta3.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4539308/plugin.video.hbogoeu-2.5.11-matrix-beta3.zip)

**Comment by arvvoid** [comment]
@rocknrollnor New test version is ready, should be ok, please test and let me know.

**Comment by arvvoid** [comment]
Leia:
[plugin.video.hbogoeu-2.5.11-leia-beta4.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4539477/plugin.video.hbogoeu-2.5.11-leia-beta4.zip)

Matrix:
[plugin.video.hbogoeu-2.5.11-matrix-beta4.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4539482/plugin.video.hbogoeu-2.5.11-matrix-beta4.zip)

**Comment by arvvoid** [comment]
@rocknrollnor Ping, not sure if you noticed new test version :)

**Comment by arvvoid** [comment]
Hello, @Sakerdot @sanangel @PolliSoft @macardi @jhdgghost @jumakki @Evili84 @haakobja if someone has some free time I would like to ask some help in testing this.

**Comment by rocknrollnor** [comment]
It works :)

**Comment by arvvoid** [comment]
@rocknrollnor ok perfect. So the problem with subtitles is gone as well in the mentioned titles in the issue?

**Comment by rocknrollnor** [comment]
Yes

**Comment by arvvoid** [comment]
Ok, I will tag the issue as fixed. 
Now I just need someone that can, to test this on a recent build of Kodi 19 (alpha, test only on isolated test device/virtual machine) and then I can merge this and release.

**Pull request merged**
